/**
 * Demo data fixtures for seeding the database with Task Cockpit test scenarios.
 * All IDs use a `demo_` prefix for easy identification and cleanup.
 * All dates are relative to the current time (Date.now()).
 */

const now = Date.now();
const daysAgo = (days: number) => now - days * 86_400_000;
const daysFrom = (days: number) => now + days * 86_400_000;
const today = now;

export const DEMO_PROJECT_ID = 'demo_project_1';

export const DEMO_FIXTURES = {
  // 4 contacts for the project
  contacts: [
    {
      id: 'demo_contact_owner',
      name: 'Demo Owner',
      roles: JSON.stringify(['owner']),
      phone: '0400 000 000',
      trade: null,
      email: null,
      address: null,
      rate: null,
      notes: 'Owner-builder',
      createdAt: daysAgo(90),
      updatedAt: daysAgo(90),
    },
    {
      id: 'demo_contact_jake',
      name: 'Jake Conlon',
      roles: JSON.stringify(['subcontractor']),
      phone: '0412 000 001',
      trade: 'Scaffolding',
      email: 'jake@scaffold.com.au',
      address: null,
      rate: null,
      notes: 'Experienced scaffold contractor',
      createdAt: daysAgo(60),
      updatedAt: daysAgo(60),
    },
    {
      id: 'demo_contact_maria',
      name: 'Maria Silva',
      roles: JSON.stringify(['subcontractor']),
      phone: '0412 000 002',
      trade: 'Painting & Interiors',
      email: 'maria@interiors.com.au',
      address: null,
      rate: null,
      notes: 'Painting and interior finishes specialist',
      createdAt: daysAgo(60),
      updatedAt: daysAgo(60),
    },
    {
      id: 'demo_contact_tom',
      name: 'Tom O\'Brien',
      roles: JSON.stringify(['subcontractor']),
      phone: '0412 000 003',
      trade: 'General Builder',
      email: 'tom@builder.com.au',
      address: null,
      rate: null,
      notes: 'General building and construction',
      createdAt: daysAgo(60),
      updatedAt: daysAgo(60),
    },
  ],

  // 1 property (the site)
  property: {
    id: 'demo_property_1',
    street: '42 Greenwood Drive',
    city: 'Kellyville',
    state: 'NSW',
    postalCode: '2155',
    country: 'Australia',
    address: '42 Greenwood Drive, Kellyville NSW 2155',
    propertyType: 'residential' as const,
    ownerId: 'demo_contact_owner',
    latitude: -33.7213,
    longitude: 150.9726,
    lotSize: null,
    lotSizeUnit: null,
    yearBuilt: null,
    meta: null,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(90),
  },

  // 1 project
  project: {
    id: 'demo_project_1',
    propertyId: 'demo_property_1',
    ownerId: 'demo_contact_owner',
    name: 'Greenwood Residential Extension',
    description:
      'Single-storey rear extension including new bedroom, bathroom, and alfresco area.',
    status: 'in_progress' as const,
    startDate: daysAgo(60),
    expectedEndDate: daysFrom(90),
    budget: 180000,
    currency: 'AUD',
    meta: null,
    createdAt: daysAgo(65),
    updatedAt: daysAgo(30),
  },

  // 20 tasks covering all scenarios
  tasks: [
    // Scenario 1: Completed Foundation Chain (background)
    {
      id: 'demo_task_t01',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Site Survey & Soil Report',
      description: 'Complete site survey and soil testing',
      notes: 'Completed on time',
      isScheduled: true,
      scheduledAt: daysAgo(55),
      dueDate: daysAgo(55),
      assignedTo: null,
      status: 'completed' as const,
      priority: 'low' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: daysAgo(55),
      createdAt: daysAgo(65),
      updatedAt: daysAgo(55),
    },
    {
      id: 'demo_task_t02',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Council DA Approval',
      description: 'Obtain Development Approval from council',
      notes: 'Completed on time',
      isScheduled: true,
      scheduledAt: daysAgo(40),
      dueDate: daysAgo(40),
      assignedTo: null,
      status: 'completed' as const,
      priority: 'high' as const,
      subcontractorId: null,
      isCriticalPath: true,
      completedDate: daysAgo(40),
      createdAt: daysAgo(60),
      updatedAt: daysAgo(40),
    },
    {
      id: 'demo_task_t03',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Concrete Slab Pour',
      description: 'Pour structural concrete slab',
      notes: 'Completed on time',
      isScheduled: true,
      scheduledAt: daysAgo(20),
      dueDate: daysAgo(20),
      assignedTo: null,
      status: 'completed' as const,
      priority: 'high' as const,
      subcontractorId: null,
      isCriticalPath: true,
      completedDate: daysAgo(20),
      createdAt: daysAgo(35),
      updatedAt: daysAgo(20),
    },

    // Scenario 1: Blocker Chain (High Priority)
    {
      id: 'demo_task_t04',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'External Cladding',
      description: 'Install external cladding to all walls',
      notes: 'Root blocker - waiting on material delivery',
      isScheduled: true,
      scheduledAt: daysAgo(6),
      dueDate: daysAgo(3),
      assignedTo: null,
      status: 'blocked' as const,
      priority: 'urgent' as const,
      subcontractorId: 'demo_contact_jake',
      isCriticalPath: true,
      completedDate: null,
      createdAt: daysAgo(30),
      updatedAt: daysAgo(2),
    },
    {
      id: 'demo_task_t05',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Scaffold Assembly',
      description: 'Assemble and secure scaffolding for cladding work',
      notes: 'Blocked by External Cladding task',
      isScheduled: true,
      scheduledAt: daysAgo(1),
      dueDate: daysAgo(1),
      assignedTo: null,
      status: 'blocked' as const,
      priority: 'high' as const,
      subcontractorId: 'demo_contact_jake',
      isCriticalPath: true,
      completedDate: null,
      createdAt: daysAgo(25),
      updatedAt: daysAgo(1),
    },
    {
      id: 'demo_task_t06',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Interior Fitout Prep',
      description: 'Prepare interior areas for fitout work',
      notes: 'Multi-hop blocking - waiting on Scaffold Assembly',
      isScheduled: true,
      scheduledAt: daysFrom(10),
      dueDate: daysFrom(7),
      assignedTo: null,
      status: 'pending' as const,
      priority: 'medium' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: null,
      createdAt: daysAgo(20),
      updatedAt: daysAgo(15),
    },

    // Scenario 2: Focus-3 Critical-Path Tasks
    {
      id: 'demo_task_t07',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Frame Roof Plates',
      description: 'Frame and install roof plates',
      notes: '3 days overdue - highest priority',
      isScheduled: true,
      scheduledAt: daysAgo(6),
      dueDate: daysAgo(3),
      assignedTo: null,
      status: 'in_progress' as const,
      priority: 'urgent' as const,
      subcontractorId: null,
      isCriticalPath: true,
      completedDate: null,
      createdAt: daysAgo(15),
      updatedAt: daysAgo(3),
    },
    {
      id: 'demo_task_t08',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Window & Door Rough-In',
      description: 'Install window and door frames',
      notes: 'Due today - second priority',
      isScheduled: true,
      scheduledAt: today,
      dueDate: today,
      assignedTo: null,
      status: 'pending' as const,
      priority: 'high' as const,
      subcontractorId: null,
      isCriticalPath: true,
      completedDate: null,
      createdAt: daysAgo(12),
      updatedAt: daysAgo(1),
    },
    {
      id: 'demo_task_t09',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Roof Batten Install',
      description: 'Install roof battens',
      notes: '5 days left - third priority. Waits on Frame Roof Plates.',
      isScheduled: true,
      scheduledAt: daysFrom(8),
      dueDate: daysFrom(5),
      assignedTo: null,
      status: 'pending' as const,
      priority: 'high' as const,
      subcontractorId: null,
      isCriticalPath: true,
      completedDate: null,
      createdAt: daysAgo(10),
      updatedAt: daysAgo(5),
    },

    // Scenario 3: Bottom Sheet - Prerequisites + Next-In-Line
    {
      id: 'demo_task_t10',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Tile Laying — Main Bathroom',
      description: 'Install tiles in main bathroom',
      notes: 'Next-in-line task waiting on External Cladding',
      isScheduled: true,
      scheduledAt: daysFrom(12),
      dueDate: daysFrom(10),
      assignedTo: null,
      status: 'pending' as const,
      priority: 'high' as const,
      subcontractorId: 'demo_contact_maria',
      isCriticalPath: false,
      completedDate: null,
      createdAt: daysAgo(8),
      updatedAt: daysAgo(5),
    },
    {
      id: 'demo_task_t18',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Paint Works — Exterior',
      description: 'Paint exterior walls and trim',
      notes: 'Second next-in-line task waiting on External Cladding',
      isScheduled: true,
      scheduledAt: daysFrom(35),
      dueDate: daysFrom(30),
      assignedTo: null,
      status: 'pending' as const,
      priority: 'medium' as const,
      subcontractorId: 'demo_contact_maria',
      isCriticalPath: false,
      completedDate: null,
      createdAt: daysAgo(5),
      updatedAt: daysAgo(3),
    },

    // Scenario 4: Quick Actions (Photo + Call)
    {
      id: 'demo_task_t11',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Site Safety Inspection',
      description: 'Conduct safety inspection of work site',
      notes: 'Quick Actions demo - has photos and subcontractor contact',
      isScheduled: true,
      scheduledAt: daysFrom(2),
      dueDate: daysFrom(2),
      assignedTo: null,
      status: 'in_progress' as const,
      priority: 'urgent' as const,
      subcontractorId: 'demo_contact_tom',
      isCriticalPath: false,
      completedDate: null,
      createdAt: daysAgo(7),
      updatedAt: daysAgo(2),
    },

    // Scenario 5: Mixed Portfolio (Edge Cases)
    {
      id: 'demo_task_t12',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Materials Order — Timber',
      description: 'Order timber materials',
      notes: null,
      isScheduled: true,
      scheduledAt: daysAgo(12),
      dueDate: daysAgo(10),
      assignedTo: null,
      status: 'completed' as const,
      priority: 'low' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: daysAgo(10),
      createdAt: daysAgo(25),
      updatedAt: daysAgo(10),
    },
    {
      id: 'demo_task_t13',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Materials Order — Roofing',
      description: 'Order roofing materials',
      notes: null,
      isScheduled: true,
      scheduledAt: daysAgo(9),
      dueDate: daysAgo(7),
      assignedTo: null,
      status: 'completed' as const,
      priority: 'low' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: daysAgo(7),
      createdAt: daysAgo(22),
      updatedAt: daysAgo(7),
    },
    {
      id: 'demo_task_t14',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Skip Bin Hire',
      description: 'Arrange skip bin for waste removal',
      notes: null,
      isScheduled: true,
      scheduledAt: daysAgo(7),
      dueDate: daysAgo(5),
      assignedTo: null,
      status: 'completed' as const,
      priority: 'low' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: daysAgo(5),
      createdAt: daysAgo(20),
      updatedAt: daysAgo(5),
    },
    {
      id: 'demo_task_t15',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Electrical Rough-In',
      description: 'First fix electrical installation',
      notes: 'Replaced by variation',
      isScheduled: true,
      scheduledAt: daysFrom(16),
      dueDate: daysFrom(14),
      assignedTo: null,
      status: 'cancelled' as const,
      priority: 'medium' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: null,
      createdAt: daysAgo(18),
      updatedAt: daysAgo(10),
    },
    {
      id: 'demo_task_t16',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Plumbing Rough-In',
      description: 'First fix plumbing installation',
      notes: 'No blocking context - tests UI resilience',
      isScheduled: true,
      scheduledAt: daysFrom(16),
      dueDate: daysFrom(14),
      assignedTo: null,
      status: 'pending' as const,
      priority: 'medium' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: null,
      createdAt: daysAgo(17),
      updatedAt: daysAgo(10),
    },
    {
      id: 'demo_task_t17',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Insulation Install',
      description: 'Install wall and roof insulation',
      notes: null,
      isScheduled: true,
      scheduledAt: daysFrom(23),
      dueDate: daysFrom(21),
      assignedTo: null,
      status: 'pending' as const,
      priority: 'low' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: null,
      createdAt: daysAgo(15),
      updatedAt: daysAgo(10),
    },
    {
      id: 'demo_task_t19',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Final Council Inspection',
      description: 'Final approval inspection by council',
      notes: 'Project end milestone',
      isScheduled: true,
      scheduledAt: daysFrom(87),
      dueDate: daysFrom(85),
      assignedTo: null,
      status: 'pending' as const,
      priority: 'high' as const,
      subcontractorId: null,
      isCriticalPath: true,
      completedDate: null,
      createdAt: daysAgo(12),
      updatedAt: daysAgo(10),
    },
    {
      id: 'demo_task_t20',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Site Cleanup & Handover',
      description: 'Final site cleanup and handover',
      notes: null,
      isScheduled: true,
      scheduledAt: daysFrom(82),
      dueDate: daysFrom(80),
      assignedTo: null,
      status: 'pending' as const,
      priority: 'low' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: null,
      createdAt: daysAgo(10),
      updatedAt: daysAgo(8),
    },
  ],

  // Task dependencies
  dependencies: [
    // Foundation chain
    { taskId: 'demo_task_t02', dependsOnTaskId: 'demo_task_t01', createdAt: daysAgo(60) },
    { taskId: 'demo_task_t03', dependsOnTaskId: 'demo_task_t02', createdAt: daysAgo(45) },

    // Blocker chain
    { taskId: 'demo_task_t04', dependsOnTaskId: 'demo_task_t03', createdAt: daysAgo(30) },
    { taskId: 'demo_task_t05', dependsOnTaskId: 'demo_task_t04', createdAt: daysAgo(25) },
    { taskId: 'demo_task_t06', dependsOnTaskId: 'demo_task_t05', createdAt: daysAgo(20) },

    // Focus-3 chaining
    { taskId: 'demo_task_t09', dependsOnTaskId: 'demo_task_t07', createdAt: daysAgo(10) },

    // Bottom Sheet next-in-line
    { taskId: 'demo_task_t10', dependsOnTaskId: 'demo_task_t04', createdAt: daysAgo(8) },
    { taskId: 'demo_task_t18', dependsOnTaskId: 'demo_task_t04', createdAt: daysAgo(5) },
  ],

  // Delay reasons
  delayReasons: [
    {
      id: 'demo_delay_t04_1',
      taskId: 'demo_task_t04',
      reasonTypeId: 'material_delay',
      notes: 'Cladding panels back-ordered from supplier — no confirmed ETA. Contractor notified 2026-03-03.',
      delayDurationDays: 5,
      delayDate: daysAgo(3),
      actor: 'Jake Conlon',
      createdAt: daysAgo(3),
    },
  ],

  // Documents (photos linked to task)
  documents: [
    {
      id: 'demo_doc_photo_1',
      projectId: 'demo_project_1',
      taskId: 'demo_task_t11',
      type: 'photo',
      title: 'Scaffold base anchor check',
      filename: 'photo_scaffold.jpg',
      mimeType: 'image/jpeg',
      size: 12000,
      status: 'local-only' as const,
      localPath: 'assets/demo/photo_scaffold.jpg',
      storageKey: null,
      cloudUrl: null,
      uri: null,
      issuedBy: null,
      issuedDate: null,
      expiresAt: null,
      notes: 'Sample photo showing scaffold installation base',
      tags: JSON.stringify(['safety', 'scaffold', 'inspection']),
      ocrText: null,
      source: 'manual',
      uploadedBy: null,
      uploadedAt: null,
      checksum: null,
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
    {
      id: 'demo_doc_photo_2',
      projectId: 'demo_project_1',
      taskId: 'demo_task_t11',
      type: 'photo',
      title: 'Safety net inspection front',
      filename: 'photo_safety_net.jpg',
      mimeType: 'image/jpeg',
      size: 12000,
      status: 'local-only' as const,
      localPath: 'assets/demo/photo_safety_net.jpg',
      storageKey: null,
      cloudUrl: null,
      uri: null,
      issuedBy: null,
      issuedDate: null,
      expiresAt: null,
      notes: 'Sample photo showing safety net installation',
      tags: JSON.stringify(['safety', 'nets', 'inspection']),
      ocrText: null,
      source: 'manual',
      uploadedBy: null,
      uploadedAt: null,
      checksum: null,
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
  ],
};
