/**
 * Demo data fixtures for seeding the database with Task Cockpit test scenarios.
 * All IDs use a `demo_` prefix for easy identification and cleanup.
 * All dates are relative to the current time (Date.now()).
 */

const now = Date.now();
const daysAgo = (days: number) => now - days * 86_400_000;
const daysFrom = (days: number) => now + days * 86_400_000;
const today = now;

export const DEMO_PROJECT_ID = 'demo_project_1';

export const DEMO_FIXTURES = {
  // 4 contacts for the project
  contacts: [
    {
      id: 'demo_contact_owner',
      name: 'Demo Owner',
      roles: JSON.stringify(['owner']),
      phone: '0400 000 000',
      trade: null,
      email: null,
      address: null,
      rate: null,
      notes: 'Owner-builder',
      createdAt: daysAgo(90),
      updatedAt: daysAgo(90),
    },
    {
      id: 'demo_contact_jake',
      name: 'Jake Conlon',
      roles: JSON.stringify(['subcontractor']),
      phone: '0412 000 001',
      trade: 'Scaffolding',
      email: 'jake@scaffold.com.au',
      address: '5 Scaffold St, Parramatta NSW 2150',
      rate: null,
      notes: 'Experienced scaffold contractor',
      createdAt: daysAgo(60),
      updatedAt: daysAgo(60),
    },
    {
      id: 'demo_contact_maria',
      name: 'Maria Silva',
      roles: JSON.stringify(['subcontractor']),
      phone: '0412 000 002',
      trade: 'Painting & Interiors',
      email: 'maria@interiors.com.au',
      address: '8 Palette Lane, Strathfield NSW 2135',
      rate: null,
      notes: 'Painting and interior finishes specialist',
      createdAt: daysAgo(60),
      updatedAt: daysAgo(60),
    },
    {
      id: 'demo_contact_tom',
      name: 'Tom O\'Brien',
      roles: JSON.stringify(['subcontractor']),
      phone: '0412 000 003',
      trade: 'General Builder',
      email: 'tom@builder.com.au',
      address: '22 Builder Way, Penrith NSW 2750',
      rate: null,
      notes: 'General building and construction',
      createdAt: daysAgo(60),
      updatedAt: daysAgo(60),
    },
    {
      id: 'demo_contact_abc',
      name: 'ABC Construction Co.',
      roles: JSON.stringify(['subcontractor']),
      phone: '02 9000 1234',
      trade: 'Structural & Framing',
      email: 'accounts@abcconstruction.com.au',
      address: '12 Industrial Ave, Penrith NSW 2750',
      rate: null,
      notes: 'Primary structural contractor for frame and roofing works',
      createdAt: daysAgo(70),
      updatedAt: daysAgo(70),
    },
  ],

  // 1 property (the site)
  property: {
    id: 'demo_property_1',
    street: '42 Greenwood Drive',
    city: 'Kellyville',
    state: 'NSW',
    postalCode: '2155',
    country: 'Australia',
    address: '42 Greenwood Drive, Kellyville NSW 2155',
    propertyType: 'residential' as const,
    ownerId: 'demo_contact_owner',
    latitude: -33.7213,
    longitude: 150.9726,
    lotSize: null,
    lotSizeUnit: null,
    yearBuilt: null,
    meta: null,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(90),
  },

  // 1 project
  project: {
    id: 'demo_project_1',
    propertyId: 'demo_property_1',
    ownerId: 'demo_contact_owner',
    name: 'Greenwood Residential Extension',
    description:
      'Single-storey rear extension including new bedroom, bathroom, and alfresco area.',
    status: 'in_progress' as const,
    startDate: daysAgo(60),
    expectedEndDate: daysFrom(90),
    budget: 180000,
    currency: 'AUD',
    meta: null,
    createdAt: daysAgo(65),
    updatedAt: daysAgo(30),
  },

  // 20 tasks covering all scenarios
  tasks: [
    // Scenario 1: Completed Foundation Chain (background)
    {
      id: 'demo_task_t01',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Site Survey & Soil Report',
      description: 'Complete site survey and soil testing',
      notes: 'Completed on time',
      isScheduled: true,
      scheduledAt: daysAgo(55),
      dueDate: daysAgo(55),
      assignedTo: null,
      status: 'completed' as const,
      priority: 'low' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: daysAgo(55),
      createdAt: daysAgo(65),
      updatedAt: daysAgo(55),
    },
    {
      id: 'demo_task_t02',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Council DA Approval',
      description: 'Obtain Development Approval from council',
      notes: 'Completed on time',
      isScheduled: true,
      scheduledAt: daysAgo(40),
      dueDate: daysAgo(40),
      assignedTo: null,
      status: 'completed' as const,
      priority: 'high' as const,
      subcontractorId: null,
      isCriticalPath: true,
      completedDate: daysAgo(40),
      createdAt: daysAgo(60),
      updatedAt: daysAgo(40),
    },
    {
      id: 'demo_task_t03',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Concrete Slab Pour',
      description: 'Pour structural concrete slab',
      notes: 'Completed on time',
      isScheduled: true,
      scheduledAt: daysAgo(20),
      dueDate: daysAgo(20),
      assignedTo: null,
      status: 'completed' as const,
      priority: 'high' as const,
      subcontractorId: 'demo_contact_tom',
      isCriticalPath: true,
      completedDate: daysAgo(20),
      taskType: 'contract_work' as const,
      quoteAmount: 6500,
      quoteStatus: 'accepted' as const,
      quoteInvoiceId: 'demo_inv_004',
      createdAt: daysAgo(35),
      updatedAt: daysAgo(20),
    },

    // Scenario 1: Blocker Chain (High Priority)
    {
      id: 'demo_task_t04',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'External Cladding',
      description: 'Install external cladding to all walls',
      notes: 'Root blocker - waiting on material delivery',
      isScheduled: true,
      scheduledAt: daysAgo(6),
      dueDate: daysAgo(3),
      assignedTo: null,
      status: 'blocked' as const,
      priority: 'urgent' as const,
      subcontractorId: 'demo_contact_jake',
      isCriticalPath: true,
      completedDate: null,
      taskType: 'variation' as const,
      quoteAmount: 1200,
      quoteStatus: 'accepted' as const,
      quoteInvoiceId: 'demo_inv_005',
      createdAt: daysAgo(30),
      updatedAt: daysAgo(2),
    },
    {
      id: 'demo_task_t05',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Scaffold Assembly',
      description: 'Assemble and secure scaffolding for cladding work',
      notes: 'Blocked by External Cladding task',
      isScheduled: true,
      scheduledAt: daysAgo(1),
      dueDate: daysAgo(1),
      assignedTo: null,
      status: 'blocked' as const,
      priority: 'high' as const,
      subcontractorId: 'demo_contact_jake',
      isCriticalPath: true,
      completedDate: null,
      taskType: 'contract_work' as const,
      quoteAmount: 3200,
      quoteStatus: 'accepted' as const,
      quoteInvoiceId: 'demo_inv_002',
      createdAt: daysAgo(25),
      updatedAt: daysAgo(1),
    },
    {
      id: 'demo_task_t06',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Interior Fitout Prep',
      description: 'Prepare interior areas for fitout work',
      notes: 'Multi-hop blocking - waiting on Scaffold Assembly',
      isScheduled: true,
      scheduledAt: daysFrom(10),
      dueDate: daysFrom(7),
      assignedTo: null,
      status: 'pending' as const,
      priority: 'medium' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: null,
      createdAt: daysAgo(20),
      updatedAt: daysAgo(15),
    },

    // Scenario 2: Focus-3 Critical-Path Tasks
    {
      id: 'demo_task_t07',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Frame Roof Plates',
      description: 'Frame and install roof plates',
      notes: '3 days overdue - highest priority',
      isScheduled: true,
      scheduledAt: daysAgo(6),
      dueDate: daysAgo(3),
      assignedTo: null,
      status: 'in_progress' as const,
      priority: 'urgent' as const,
      subcontractorId: 'demo_contact_abc',
      isCriticalPath: true,
      completedDate: null,
      taskType: 'contract_work' as const,
      quoteAmount: 8500,
      quoteStatus: 'accepted' as const,
      quoteInvoiceId: 'demo_inv_001',
      createdAt: daysAgo(15),
      updatedAt: daysAgo(3),
    },
    {
      id: 'demo_task_t08',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Window & Door Rough-In',
      description: 'Install window and door frames',
      notes: 'Due today - second priority',
      isScheduled: true,
      scheduledAt: today,
      dueDate: today,
      assignedTo: null,
      status: 'pending' as const,
      priority: 'high' as const,
      subcontractorId: null,
      isCriticalPath: true,
      completedDate: null,
      createdAt: daysAgo(12),
      updatedAt: daysAgo(1),
    },
    {
      id: 'demo_task_t09',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Roof Batten Install',
      description: 'Install roof battens',
      notes: '5 days left - third priority. Waits on Frame Roof Plates.',
      isScheduled: true,
      scheduledAt: daysFrom(8),
      dueDate: daysFrom(5),
      assignedTo: null,
      status: 'pending' as const,
      priority: 'high' as const,
      subcontractorId: null,
      isCriticalPath: true,
      completedDate: null,
      createdAt: daysAgo(10),
      updatedAt: daysAgo(5),
    },

    // Scenario 3: Bottom Sheet - Prerequisites + Next-In-Line
    {
      id: 'demo_task_t10',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Tile Laying — Main Bathroom',
      description: 'Install tiles in main bathroom',
      notes: 'Next-in-line task waiting on External Cladding',
      isScheduled: true,
      scheduledAt: daysFrom(12),
      dueDate: daysFrom(10),
      assignedTo: null,
      status: 'pending' as const,
      priority: 'high' as const,
      subcontractorId: 'demo_contact_maria',
      isCriticalPath: false,
      completedDate: null,
      createdAt: daysAgo(8),
      updatedAt: daysAgo(5),
    },
    {
      id: 'demo_task_t18',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Paint Works — Exterior',
      description: 'Paint exterior walls and trim',
      notes: 'Second next-in-line task waiting on External Cladding',
      isScheduled: true,
      scheduledAt: daysFrom(35),
      dueDate: daysFrom(30),
      assignedTo: null,
      status: 'pending' as const,
      priority: 'medium' as const,
      subcontractorId: 'demo_contact_maria',
      isCriticalPath: false,
      completedDate: null,
      taskType: 'contract_work' as const,
      quoteAmount: 4800,
      quoteStatus: 'accepted' as const,
      quoteInvoiceId: 'demo_inv_003',
      createdAt: daysAgo(5),
      updatedAt: daysAgo(3),
    },

    // Scenario 4: Quick Actions (Photo + Call)
    {
      id: 'demo_task_t11',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Site Safety Inspection',
      description: 'Conduct safety inspection of work site',
      notes: 'Quick Actions demo - has photos and subcontractor contact',
      isScheduled: true,
      scheduledAt: daysFrom(2),
      dueDate: daysFrom(2),
      assignedTo: null,
      status: 'in_progress' as const,
      priority: 'urgent' as const,
      subcontractorId: 'demo_contact_tom',
      isCriticalPath: false,
      completedDate: null,
      createdAt: daysAgo(7),
      updatedAt: daysAgo(2),
    },

    // Scenario 5: Mixed Portfolio (Edge Cases)
    {
      id: 'demo_task_t12',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Materials Order — Timber',
      description: 'Order timber materials',
      notes: null,
      isScheduled: true,
      scheduledAt: daysAgo(12),
      dueDate: daysAgo(10),
      assignedTo: null,
      status: 'completed' as const,
      priority: 'low' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: daysAgo(10),
      createdAt: daysAgo(25),
      updatedAt: daysAgo(10),
    },
    {
      id: 'demo_task_t13',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Materials Order — Roofing',
      description: 'Order roofing materials',
      notes: null,
      isScheduled: true,
      scheduledAt: daysAgo(9),
      dueDate: daysAgo(7),
      assignedTo: null,
      status: 'completed' as const,
      priority: 'low' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: daysAgo(7),
      createdAt: daysAgo(22),
      updatedAt: daysAgo(7),
    },
    {
      id: 'demo_task_t14',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Skip Bin Hire',
      description: 'Arrange skip bin for waste removal',
      notes: null,
      isScheduled: true,
      scheduledAt: daysAgo(7),
      dueDate: daysAgo(5),
      assignedTo: null,
      status: 'completed' as const,
      priority: 'low' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: daysAgo(5),
      createdAt: daysAgo(20),
      updatedAt: daysAgo(5),
    },
    {
      id: 'demo_task_t15',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Electrical Rough-In',
      description: 'First fix electrical installation',
      notes: 'Replaced by variation',
      isScheduled: true,
      scheduledAt: daysFrom(16),
      dueDate: daysFrom(14),
      assignedTo: null,
      status: 'cancelled' as const,
      priority: 'medium' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: null,
      createdAt: daysAgo(18),
      updatedAt: daysAgo(10),
    },
    {
      id: 'demo_task_t16',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Plumbing Rough-In',
      description: 'First fix plumbing installation',
      notes: 'No blocking context - tests UI resilience',
      isScheduled: true,
      scheduledAt: daysFrom(16),
      dueDate: daysFrom(14),
      assignedTo: null,
      status: 'pending' as const,
      priority: 'medium' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: null,
      createdAt: daysAgo(17),
      updatedAt: daysAgo(10),
    },
    {
      id: 'demo_task_t17',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Insulation Install',
      description: 'Install wall and roof insulation',
      notes: null,
      isScheduled: true,
      scheduledAt: daysFrom(23),
      dueDate: daysFrom(21),
      assignedTo: null,
      status: 'pending' as const,
      priority: 'low' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: null,
      createdAt: daysAgo(15),
      updatedAt: daysAgo(10),
    },
    {
      id: 'demo_task_t19',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Final Council Inspection',
      description: 'Final approval inspection by council',
      notes: 'Project end milestone',
      isScheduled: true,
      scheduledAt: daysFrom(87),
      dueDate: daysFrom(85),
      assignedTo: null,
      status: 'pending' as const,
      priority: 'high' as const,
      subcontractorId: null,
      isCriticalPath: true,
      completedDate: null,
      createdAt: daysAgo(12),
      updatedAt: daysAgo(10),
    },
    {
      id: 'demo_task_t20',
      projectId: 'demo_project_1',
      phaseId: null,
      title: 'Site Cleanup & Handover',
      description: 'Final site cleanup and handover',
      notes: null,
      isScheduled: true,
      scheduledAt: daysFrom(82),
      dueDate: daysFrom(80),
      assignedTo: null,
      status: 'pending' as const,
      priority: 'low' as const,
      subcontractorId: null,
      isCriticalPath: false,
      completedDate: null,
      createdAt: daysAgo(10),
      updatedAt: daysAgo(8),
    },
  ],

  // Task dependencies
  dependencies: [
    // Foundation chain
    { taskId: 'demo_task_t02', dependsOnTaskId: 'demo_task_t01', createdAt: daysAgo(60) },
    { taskId: 'demo_task_t03', dependsOnTaskId: 'demo_task_t02', createdAt: daysAgo(45) },

    // Blocker chain
    { taskId: 'demo_task_t04', dependsOnTaskId: 'demo_task_t03', createdAt: daysAgo(30) },
    { taskId: 'demo_task_t05', dependsOnTaskId: 'demo_task_t04', createdAt: daysAgo(25) },
    { taskId: 'demo_task_t06', dependsOnTaskId: 'demo_task_t05', createdAt: daysAgo(20) },

    // Focus-3 chaining
    { taskId: 'demo_task_t09', dependsOnTaskId: 'demo_task_t07', createdAt: daysAgo(10) },

    // Bottom Sheet next-in-line
    { taskId: 'demo_task_t10', dependsOnTaskId: 'demo_task_t04', createdAt: daysAgo(8) },
    { taskId: 'demo_task_t18', dependsOnTaskId: 'demo_task_t04', createdAt: daysAgo(5) },
  ],

  // Delay reasons
  delayReasons: [
    {
      id: 'demo_delay_t04_1',
      taskId: 'demo_task_t04',
      reasonTypeId: 'material_delay',
      notes: 'Cladding panels back-ordered from supplier — no confirmed ETA. Contractor notified 2026-03-03.',
      delayDurationDays: 5,
      delayDate: daysAgo(3),
      actor: 'Jake Conlon',
      createdAt: daysAgo(3),
    },
  ],

  // ── Quotations ────────────────────────────────────────────────────
  //  4 accepted quotations — vendor details frozen at acceptance time
  quotations: [
    {
      // Jake Conlon — Scaffold Assembly (accepted)
      id: 'demo_quot_001',
      reference: 'QUOT-2026-SC01',
      projectId: 'demo_project_1',
      taskId: 'demo_task_t05',
      documentId: null,
      vendorId: 'demo_contact_jake',
      vendorName: 'Jake Conlon',
      vendorAddress: '5 Scaffold St, Parramatta NSW 2150',
      vendorEmail: 'jake@scaffold.com.au',
      date: daysAgo(12),
      expiryDate: daysFrom(18),
      currency: 'AUD',
      subtotal: 2909.09,
      taxTotal: 290.91,
      total: 3200.00,
      lineItems: JSON.stringify([
        { description: 'Scaffold erection & hire (4 weeks)', qty: 4, unit: 'week', unitPrice: 727.27, total: 2909.09 },
      ]),
      notes: 'Quote accepted — scaffold works to proceed on cleared site.',
      status: 'accepted' as const,
      createdAt: daysAgo(12),
      updatedAt: daysAgo(9),
      deletedAt: null,
    },
    {
      // ABC Construction Co. — Frame Roof Plates (accepted)
      id: 'demo_quot_002',
      reference: 'QUOT-2026-ABC01',
      projectId: 'demo_project_1',
      taskId: 'demo_task_t07',
      documentId: null,
      vendorId: 'demo_contact_abc',
      vendorName: 'ABC Construction Co.',
      vendorAddress: '12 Industrial Ave, Penrith NSW 2750',
      vendorEmail: 'accounts@abcconstruction.com.au',
      date: daysAgo(32),
      expiryDate: daysFrom(28),
      currency: 'AUD',
      subtotal: 7727.27,
      taxTotal: 772.73,
      total: 8500.00,
      lineItems: JSON.stringify([
        { description: 'Structural framing — walls & roof plates', qty: 1, unit: 'lump sum', unitPrice: 5500.00, total: 5500.00 },
        { description: 'Roof batten supply & fix', qty: 1, unit: 'lump sum', unitPrice: 2227.27, total: 2227.27 },
      ]),
      notes: 'Quote accepted. Invoice INV-2026-0041 raised.',
      status: 'accepted' as const,
      createdAt: daysAgo(32),
      updatedAt: daysAgo(28),
      deletedAt: null,
    },
    {
      // Maria Silva — Paint Works Exterior (accepted)
      id: 'demo_quot_003',
      reference: 'QUOT-2026-MS01',
      projectId: 'demo_project_1',
      taskId: 'demo_task_t18',
      documentId: null,
      vendorId: 'demo_contact_maria',
      vendorName: 'Maria Silva',
      vendorAddress: '8 Palette Lane, Strathfield NSW 2135',
      vendorEmail: 'maria@interiors.com.au',
      date: daysAgo(25),
      expiryDate: daysFrom(35),
      currency: 'AUD',
      subtotal: 4363.64,
      taxTotal: 436.36,
      total: 4800.00,
      lineItems: JSON.stringify([
        { description: 'Exterior painting — primer & 2 coats all walls', qty: 1, unit: 'lump sum', unitPrice: 4363.64, total: 4363.64 },
      ]),
      notes: 'Quote accepted. Deposit invoice raised; balance due on completion.',
      status: 'accepted' as const,
      createdAt: daysAgo(25),
      updatedAt: daysAgo(22),
      deletedAt: null,
    },
    {
      // Tom O'Brien — Concrete Slab Pour (accepted, fully paid)
      id: 'demo_quot_004',
      reference: 'QUOT-2026-TB01',
      projectId: 'demo_project_1',
      taskId: 'demo_task_t03',
      documentId: null,
      vendorId: 'demo_contact_tom',
      vendorName: "Tom O'Brien",
      vendorAddress: '22 Builder Way, Penrith NSW 2750',
      vendorEmail: 'tom@builder.com.au',
      date: daysAgo(38),
      expiryDate: daysFrom(22),
      currency: 'AUD',
      subtotal: 5909.09,
      taxTotal: 590.91,
      total: 6500.00,
      lineItems: JSON.stringify([
        { description: 'Concrete formwork & pour — slab on ground', qty: 1, unit: 'lump sum', unitPrice: 4000.00, total: 4000.00 },
        { description: 'Termite barrier installation', qty: 1, unit: 'lump sum', unitPrice: 1909.09, total: 1909.09 },
      ]),
      notes: 'Quote accepted. Fully paid — INV-2026-0029.',
      status: 'accepted' as const,
      createdAt: daysAgo(38),
      updatedAt: daysAgo(30),
      deletedAt: null,
    },
  ],

  // ── Invoices ──────────────────────────────────────────────────────
  //  5 scenarios: overdue-unpaid, due-soon, partial, paid, draft-variation
  invoices: [
    {
      // Overdue — ABC Construction Co. structural framing invoice
      id: 'demo_inv_001',
      projectId: 'demo_project_1',
      externalId: 'INV-2026-0041',
      externalReference: null,
      issuerName: 'ABC Construction Co.',
      issuerAddress: '12 Industrial Ave, Penrith NSW 2750',
      issuerTaxId: 'ABN 12 345 678 901',
      recipientName: 'Demo Owner',
      recipientId: 'demo_contact_owner',
      total: 8500.00,
      subtotal: 7727.27,
      tax: 772.73,
      currency: 'AUD',
      dateIssued: daysAgo(28),
      dateDue: daysAgo(14),
      paymentDate: null,
      status: 'submitted',
      paymentStatus: 'unpaid',
      documentId: null,
      lineItems: JSON.stringify([
        { description: 'Structural framing — walls & roof plates', qty: 1, unit: 'lump sum', unitPrice: 5500.00, total: 5500.00 },
        { description: 'Roof batten supply & fix', qty: 1, unit: 'lump sum', unitPrice: 2227.27, total: 2227.27 },
      ]),
      tags: JSON.stringify(['framing', 'structural']),
      notes: 'OVERDUE — payment was due 14 days ago. Please arrange transfer urgently.',
      metadata: JSON.stringify({ vendorSource: 'contact', contractorName: 'ABC Construction Co.', paymentCategory: 'contract' }),
      taskId: 'demo_task_t07',
      quoteId: 'demo_quot_002',
      createdAt: daysAgo(28),
      updatedAt: daysAgo(14),
      deletedAt: null,
    },
    {
      // Due soon — Jake Conlon scaffolding invoice
      id: 'demo_inv_002',
      projectId: 'demo_project_1',
      externalId: 'INV-2026-0044',
      externalReference: null,
      issuerName: 'Jake Conlon',
      issuerAddress: '5 Scaffold St, Parramatta NSW 2150',
      issuerTaxId: 'ABN 55 431 768 201',
      recipientName: 'Demo Owner',
      recipientId: 'demo_contact_owner',
      total: 3200.00,
      subtotal: 2909.09,
      tax: 290.91,
      currency: 'AUD',
      dateIssued: daysAgo(9),
      dateDue: daysFrom(5),
      paymentDate: null,
      status: 'submitted',
      paymentStatus: 'unpaid',
      documentId: null,
      lineItems: JSON.stringify([
        { description: 'Scaffold erection & hire (4 weeks)', qty: 4, unit: 'week', unitPrice: 727.27, total: 2909.09 },
      ]),
      tags: JSON.stringify(['scaffolding']),
      notes: null,
      metadata: JSON.stringify({ vendorSource: 'contact', contractorName: 'Jake Conlon', paymentCategory: 'contract' }),
      taskId: 'demo_task_t05',
      quoteId: 'demo_quot_001',
      createdAt: daysAgo(9),
      updatedAt: daysAgo(9),
      deletedAt: null,
    },
    {
      // Partially paid — Maria Silva interior/painting
      id: 'demo_inv_003',
      projectId: 'demo_project_1',
      externalId: 'INV-2026-0038',
      externalReference: null,
      issuerName: 'Maria Silva',
      issuerAddress: '8 Palette Lane, Strathfield NSW 2135',
      issuerTaxId: 'ABN 73 819 204 567',
      recipientName: 'Demo Owner',
      recipientId: 'demo_contact_owner',
      total: 4800.00,
      subtotal: 4363.64,
      tax: 436.36,
      currency: 'AUD',
      dateIssued: daysAgo(22),
      dateDue: daysFrom(12),
      paymentDate: null,
      status: 'approved',
      paymentStatus: 'partial',
      documentId: null,
      lineItems: JSON.stringify([
        { description: 'Internal painting — primer & 2 coats all rooms', qty: 1, unit: 'lump sum', unitPrice: 3000.00, total: 3000.00 },
        { description: 'Interior tiling prep & waterproofing', qty: 1, unit: 'lump sum', unitPrice: 1363.64, total: 1363.64 },
      ]),
      tags: JSON.stringify(['painting', 'interiors']),
      notes: 'Deposit of $2,400 received. Balance $2,400 due on completion.',
      metadata: JSON.stringify({ vendorSource: 'contact', contractorName: 'Maria Silva', paymentCategory: 'contract' }),
      taskId: 'demo_task_t18',
      quoteId: 'demo_quot_003',
      createdAt: daysAgo(22),
      updatedAt: daysAgo(8),
      deletedAt: null,
    },
    {
      // Fully paid — Tom O'Brien foundation works
      id: 'demo_inv_004',
      projectId: 'demo_project_1',
      externalId: 'INV-2026-0029',
      externalReference: null,
      issuerName: 'Tom O\'Brien',
      issuerAddress: '22 Builder Way, Penrith NSW 2750',
      issuerTaxId: 'ABN 91 027 445 883',
      recipientName: 'Demo Owner',
      recipientId: 'demo_contact_owner',
      total: 6500.00,
      subtotal: 5909.09,
      tax: 590.91,
      currency: 'AUD',
      dateIssued: daysAgo(30),
      dateDue: daysAgo(16),
      paymentDate: daysAgo(14),
      status: 'approved',
      paymentStatus: 'paid',
      documentId: null,
      lineItems: JSON.stringify([
        { description: 'Concrete formwork & pour — slab on ground', qty: 1, unit: 'lump sum', unitPrice: 4000.00, total: 4000.00 },
        { description: 'Termite barrier installation', qty: 1, unit: 'lump sum', unitPrice: 1909.09, total: 1909.09 },
      ]),
      tags: JSON.stringify(['foundation', 'concrete']),
      notes: 'Paid in full via EFT on receipt.',
      metadata: JSON.stringify({ vendorSource: 'contact', contractorName: "Tom O'Brien", paymentCategory: 'contract' }),
      taskId: 'demo_task_t03',
      quoteId: 'demo_quot_004',
      createdAt: daysAgo(30),
      updatedAt: daysAgo(14),
      deletedAt: null,
    },
    {
      // Draft variation — Jake Conlon extra scaffold hire
      id: 'demo_inv_005',
      projectId: 'demo_project_1',
      externalId: null,
      externalReference: 'VAR-2026-007',
      issuerName: 'Jake Conlon',
      issuerAddress: '5 Scaffold St, Parramatta NSW 2150',
      issuerTaxId: 'ABN 55 431 768 201',
      recipientName: 'Demo Owner',
      recipientId: 'demo_contact_owner',
      total: 1200.00,
      subtotal: 1090.91,
      tax: 109.09,
      currency: 'AUD',
      dateIssued: daysAgo(3),
      dateDue: daysFrom(20),
      paymentDate: null,
      status: 'draft',
      paymentStatus: 'unpaid',
      documentId: null,
      lineItems: JSON.stringify([
        { description: 'Variation: extended scaffold hire — cladding delay (5 days)', qty: 5, unit: 'day', unitPrice: 218.18, total: 1090.91 },
      ]),
      tags: JSON.stringify(['scaffolding', 'variation']),
      notes: 'Variation raised due to cladding material delay (ref: demo_delay_t04_1). Awaiting owner approval.',
      metadata: JSON.stringify({ vendorSource: 'contact', contractorName: 'Jake Conlon', paymentCategory: 'variation' }),
      taskId: 'demo_task_t04',
      quoteId: null,
      createdAt: daysAgo(3),
      updatedAt: daysAgo(3),
      deletedAt: null,
    },
  ],

  // ── Payments ─────────────────────────────────────────────────────
  //  6 scenarios: overdue-pending, due-soon-pending, settled,
  //               partial-deposit-settled, partial-balance-pending, variation-pending
  payments: [
    {
      // Overdue — ABC Construction frame & structure ($8,500 matches dashboard mock)
      id: 'demo_pay_001',
      projectId: 'demo_project_1',
      invoiceId: 'demo_inv_001',
      amount: 8500.00,
      currency: 'AUD',
      paymentDate: null,
      dueDate: daysAgo(14),
      status: 'pending' as const,
      paymentMethod: null,
      reference: 'INV-2026-0041',
      notes: 'OVERDUE — Frame & Structure invoice. Arrange transfer ASAP.',
      contactId: 'demo_contact_abc',
      contractorName: 'ABC Construction Co.',
      paymentCategory: 'contract' as const,
      stageLabel: 'Frame & Structure',
      createdAt: daysAgo(28),
      updatedAt: daysAgo(14),
    },
    {
      // Due soon — Jake Conlon scaffolding
      id: 'demo_pay_002',
      projectId: 'demo_project_1',
      invoiceId: 'demo_inv_002',
      amount: 3200.00,
      currency: 'AUD',
      paymentDate: null,
      dueDate: daysFrom(5),
      status: 'pending' as const,
      paymentMethod: null,
      reference: 'INV-2026-0044',
      notes: null,
      contactId: 'demo_contact_jake',
      contractorName: 'Jake Conlon',
      paymentCategory: 'contract' as const,
      stageLabel: 'Scaffolding',
      createdAt: daysAgo(9),
      updatedAt: daysAgo(9),
    },
    {
      // Settled — Tom O'Brien foundation works
      id: 'demo_pay_003',
      projectId: 'demo_project_1',
      invoiceId: 'demo_inv_004',
      amount: 6500.00,
      currency: 'AUD',
      paymentDate: daysAgo(14),
      dueDate: daysAgo(16),
      status: 'settled' as const,
      paymentMethod: 'eft',
      reference: 'INV-2026-0029',
      notes: 'Paid in full via EFT.',
      contactId: 'demo_contact_tom',
      contractorName: 'Tom O\'Brien',
      paymentCategory: 'contract' as const,
      stageLabel: 'Foundation Works',
      createdAt: daysAgo(30),
      updatedAt: daysAgo(14),
    },
    {
      // Partial deposit — Maria Silva interiors (settled)
      id: 'demo_pay_004',
      projectId: 'demo_project_1',
      invoiceId: 'demo_inv_003',
      amount: 2400.00,
      currency: 'AUD',
      paymentDate: daysAgo(8),
      dueDate: daysAgo(8),
      status: 'settled' as const,
      paymentMethod: 'eft',
      reference: 'INV-2026-0038-DEP',
      notes: 'Deposit 50% paid per agreement.',
      contactId: 'demo_contact_maria',
      contractorName: 'Maria Silva',
      paymentCategory: 'contract' as const,
      stageLabel: 'Interior Works — Deposit',
      createdAt: daysAgo(22),
      updatedAt: daysAgo(8),
    },
    {
      // Partial balance — Maria Silva interiors (pending)
      id: 'demo_pay_005',
      projectId: 'demo_project_1',
      invoiceId: 'demo_inv_003',
      amount: 2400.00,
      currency: 'AUD',
      paymentDate: null,
      dueDate: daysFrom(12),
      status: 'pending' as const,
      paymentMethod: null,
      reference: 'INV-2026-0038-BAL',
      notes: 'Balance due on practical completion of interior works.',
      contactId: 'demo_contact_maria',
      contractorName: 'Maria Silva',
      paymentCategory: 'contract' as const,
      stageLabel: 'Interior Works — Balance',
      createdAt: daysAgo(22),
      updatedAt: daysAgo(8),
    },
    {
      // Variation — Jake Conlon extended scaffold hire
      id: 'demo_pay_006',
      projectId: 'demo_project_1',
      invoiceId: 'demo_inv_005',
      amount: 1200.00,
      currency: 'AUD',
      paymentDate: null,
      dueDate: daysFrom(20),
      status: 'pending' as const,
      paymentMethod: null,
      reference: 'VAR-2026-007',
      notes: 'Variation: extended scaffold hire due to cladding delay.',
      contactId: 'demo_contact_jake',
      contractorName: 'Jake Conlon',
      paymentCategory: 'variation' as const,
      stageLabel: 'Scaffolding Variation',
      createdAt: daysAgo(3),
      updatedAt: daysAgo(3),
    },
  ],

  // Documents (photos linked to task)
  documents: [
    {
      id: 'demo_doc_photo_1',
      projectId: 'demo_project_1',
      taskId: 'demo_task_t11',
      type: 'photo',
      title: 'Scaffold base anchor check',
      filename: 'photo_scaffold.jpg',
      mimeType: 'image/jpeg',
      size: 12000,
      status: 'local-only' as const,
      localPath: 'assets/demo/photo_scaffold.jpg',
      storageKey: null,
      cloudUrl: null,
      uri: null,
      issuedBy: null,
      issuedDate: null,
      expiresAt: null,
      notes: 'Sample photo showing scaffold installation base',
      tags: JSON.stringify(['safety', 'scaffold', 'inspection']),
      ocrText: null,
      source: 'manual',
      uploadedBy: null,
      uploadedAt: null,
      checksum: null,
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
    {
      id: 'demo_doc_photo_2',
      projectId: 'demo_project_1',
      taskId: 'demo_task_t11',
      type: 'photo',
      title: 'Safety net inspection front',
      filename: 'photo_safety_net.jpg',
      mimeType: 'image/jpeg',
      size: 12000,
      status: 'local-only' as const,
      localPath: 'assets/demo/photo_safety_net.jpg',
      storageKey: null,
      cloudUrl: null,
      uri: null,
      issuedBy: null,
      issuedDate: null,
      expiresAt: null,
      notes: 'Sample photo showing safety net installation',
      tags: JSON.stringify(['safety', 'nets', 'inspection']),
      ocrText: null,
      source: 'manual',
      uploadedBy: null,
      uploadedAt: null,
      checksum: null,
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
  ],
};
